# -*- coding: utf-8 -*-
"""Sample.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tpa1HT5QjhqEv7sSCHz-O_th_JQs6jTg
"""

from google.colab import drive
drive.mount('/content/drive')

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import sklearn as skl
from sklearn.model_selection import train_test_split

dateparse = lambda dates: pd.datetime.strptime(dates, '%Y-%m-%d')
data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/a.us.txt',sep=',', index_col='Date', parse_dates=['Date'], date_parser=dateparse).fillna(0)
#plot close price
plt.figure(figsize=(10,6))
# plt.grid(True)
# plt.xlabel('Year')
# plt.ylabel('Close Prices')
plt.plot(data.loc['2004-01-01':'2004-12-31']['Close'])
plt.figure()
plt.plot(np.diff(data.loc['2004-01-01':'2004-12-31']['Close']))
plt.figure()
plt.hist(np.diff(data.loc['2004-01-01':'2004-12-31']['Close']))
# plt.title('Closing Price')
# plt.show()
plt.figure(figsize=(10,6))
# plt.grid(True)
# plt.xlabel('Year')
# plt.ylabel('Close Prices')
plt.plot(data['Close'])
plt.figure()
plt.plot(np.diff(data['Close']))
plt.figure()
plt.hist(np.diff(data['Close']))
plt.figure()
df_close = data['Close']
df_close.plot(style='k.')
plt.title('Scatter plot of closing price')
plt.show()
data.shape

train, test = train_test_split(data, test_size=0.33)
train,test